### ISSUE TITLE
markbot issues

### ISSUE THREAD

**Issue by Paulinamissio** [Paulinamissio/animal-rescue-website#1]
@hellachella

**Comment by hellachella** [comment]
## Favicon:
1. I suspect that it wasn't exported correctly. Did you use [X Icon Editor](http://www.xiconeditor.com/)? 
  *Import the icon you make in Illustrator (saved as a png) and then export as favicon
2. You only need `favicon.ico` and `favicon-196.png`.  You **don't** need to add favicon-16.ico etc.
3. Try putting it right below the `<meta>` tag

## lang en-ca:
This is a kind of confusing thing to figure out using Markbot. The problem is that your landmark roles are not assigned properly. Go back and look and landmark ARIA roles in that week's material. 

## tabindex="0":
1. Make sure to put `tabindex="0"` anywhere that you have linked to from skiplinks. 
2. Make sure the `main` skiplink is going somewhere (to the main div, it currently doesn't have its id tag)

<img width="600" alt="screen shot 2018-01-04 at 10 08 59 pm" src="https://user-images.githubusercontent.com/10465921/34593926-eb02e5b0-f19b-11e7-9e51-d07272a8e753.png">

**Comment by Paulinamissio** [comment]
@hellachella I looked through the landmark ARIA and I think I have everything properly there, I still don't understand why it's having an issue with my html (lang en-ca) tag..
